export const translations = {
  EN: {
    //mission vision values
    'mission.title': 'Our Mission',
    'mission.desc': 'To revolutionize Rwanda’s real estate sector by establishing a verification-first marketplace that eliminates fraud through direct National Land Authority integration and blockchain-backed transaction locking, while empowering stakeholders with transparent, AI-driven valuation and real-time market trends analysis.',
    'vision.title': 'Our Vision',
    'vision.desc': 'To become the digital standard for real estate trust across Rwanda, creating a future where property transfer is instant, secure, and accessible to everyone.',
    'values.integrity': 'Integrity',
    'values.innovation': 'Innovation',
    'values.access': 'Accessibility',
    //hero market analyiss
    'ml.title': 'AI Market Forecast',
    'ml.subtitle': 'Predictive analytics identifying high-yield zones before the market moves.',
    'ml.confidence': 'AI Confidence Score',
    'ml.predicted': '2026 Prediction',
    'ml.historical': 'Historical Data',
    'ml.btn.analyze': 'Analyze Full Report',
    'ml.btn.assets': 'View Assets in',
    //Our Professional Agencyes
    'community.title': 'Our Impact & Network',
    'community.subtitle': 'Meet the top performers driving the Rwandan real estate market.',
    'community.stats.volume': 'Sales Volume',
    'community.stats.sold': 'Properties Sold',
    'community.stats.agents': 'Active Agents',
    'community.agents.title': 'Top Rated Agents',
    'community.agencies.title': 'Trusted Agencies',
    'community.cta.title': 'Are you a Real Estate Professional?',
    'community.cta.subtitle': 'Join SafeLand to access verified leads, digital tools, and faster closings.',
    'community.cta.button': 'Request to Join',
    //Home Page intro section based on users live location
    'hotDeals.title': 'Hot Deals Near You',
    'hotDeals.subtitle': 'We found verified premium listings in your area.',
    'hotDeals.locating': 'Locating you...',
    'hotDeals.locationFound': 'Location Verified',
    'hotDeals.updateLocation': 'Change Location',
    'hotDeals.viewDeal': 'View Deal',
    'hotDeals.exclusive': 'Exclusive',
    //Footer Component
    'footer.mission': 'SafeLand Rwanda is the first centralized, NLA-integrated real estate marketplace ensuring zero fraud and 100% transparency.',
    'footer.newsletter.title': 'Stay Updated',
    'footer.newsletter.subtitle': 'Get the latest verified listings and market trends delivered to your inbox.',
    'footer.newsletter.placeholder': 'Enter your email address',
    'footer.newsletter.button': 'Subscribe',
    'footer.links.company': 'Company',
    'footer.links.marketplace': 'Marketplace',
    'footer.links.support': 'Support',
    'footer.contact.title': 'Contact Us',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    //Listing Page
    'market.title': 'Find Your Perfect Property',
    'market.subtitle': 'Browse verified listings across Rwanda, from residential homes to prime investment land.',
    'market.category.houses': 'Residential Houses & Villas',
    'market.category.apartments': 'Modern Apartments',
    'market.category.land': 'Land & Plots',
    'market.category.commercial': 'Commercial Real Estate',
    'market.viewAll': 'View All',
    'market.filter.all': 'All',
    'market.filter.buy': 'For Sale',
    'market.filter.rent': 'For Rent',
    'card.verified': 'Verified',
    // dashbaord content 
    'dash.nav.overview': 'Overview',
    'dash.nav.properties': 'Properties',
    'dash.nav.users': 'User Management',
    'dash.nav.analytics': 'Analytics',
    'dash.nav.settings': 'Settings',
    'dash.stats.totalSales': 'Total Sales',
    'dash.stats.activeListings': 'Active Listings',
    'dash.stats.verifiedUsers': 'Verified Users',
    'dash.welcome': 'Welcome back, Admin',
    'dash.subtitle': 'Here is what is happening with your properties today.',
    //Not Found Page
    'error.404.title': 'Page Not Found',
    'error.404.subtitle': 'We couldn’t locate the page or property you are looking for. It might have been sold or moved.',
    'error.404.backHome': 'Back to Safety',
    'error.404.search': 'Search Properties',
    'error.404.support': 'Contact Support',
    //Forgot PAssword
    'auth.forgot.title': 'Reset Password',
    'auth.forgot.subtitle': 'Enter your email and we’ll send you instructions to reset your password.',
    'auth.forgot.emailLabel': 'Registered Email Address',
    'auth.forgot.submit': 'Send Reset Link',
    'auth.forgot.backToLogin': 'Back to Login',
    'auth.forgot.successTitle': 'Check your email',
    'auth.forgot.successSubtitle': 'We have sent a password reset link to',
    'auth.forgot.resend': 'Didn’t receive the email? Click to resend',
    'auth.forgot.resendLink': 'Resend',
    // Navigation
    'nav.home': 'Home',
    'nav.marketTrends': 'Market Trends',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.properties': 'Properties',
    'nav.properties.buy': 'Buy Property',
    'nav.properties.sell': 'Sell Property',
    'nav.properties.commercial': 'Commercial Buildings',
    'nav.properties.houses': 'Houses & Apartments',
    'nav.properties.land': 'Land & Plots',
    'nav.blockers': 'Blockers',
    'nav.hotDeals': 'Hot Deals',

    // TopBar
    'topbar.login': 'Login',
    'topbar.register': 'Register',
    'topbar.toggleTheme': 'Toggle Theme',

    // Common
    'common.language.en': 'English',
    'common.language.fr': 'French',
    'common.language.kin': 'Kinyarwanda',

    // Mobile Menu
    'mobile.menu': 'Menu',
    // for hero section home
    'hero.badge': 'NLA Integrated Verification',
    'hero.headline.part1': 'Buy Land & Homes in Rwanda',
    'hero.headline.part2': 'Without the Risk.',
    'hero.subheadline.part1': 'The first decentralized marketplace powered by',
    'hero.subheadline.part2': 'NLA verification',
    'hero.subheadline.part3': 'and AI. We ensure every title deed is real, every owner is verified, and every transaction is transparent.',
    'hero.stats.verifiedTitles': 'Verified Titles',
    'hero.stats.zero': 'Zero',
    'hero.stats.fraudTolerance': 'Fraud Tolerance',
    'hero.cta.exploreMap': 'Explore Map',
    'hero.cta.listProperty': 'List Property',
    'hero.tabs.buy': 'Buy',
    'hero.tabs.rent': 'Rent',
    'hero.tabs.land': 'Land',
    'hero.form.location': 'Location',
    'hero.form.locationPlaceholder': 'Kigali, Gasabo, Kimironko...',
    'hero.form.propertyType': 'Property Type',
    'hero.propertyTypes.residential': 'Residential House',
    'hero.propertyTypes.commercial': 'Commercial Building',
    'hero.propertyTypes.land': 'Empty Plot / Land',
    'hero.propertyTypes.apartment': 'Apartment',
    'hero.form.minPrice': 'Min Price (RWF)',
    'hero.form.minPricePlaceholder': 'Min',
    'hero.form.maxPrice': 'Max Price (RWF)',
    'hero.form.maxPricePlaceholder': 'Max',
    'hero.form.searchButton': 'Find {{propertyType}}',
    'hero.backgroundAlt': 'Modern Real Estate in Rwanda',
    // --- NEW AI SEARCH KEYS ---
    'hero.form.modeAI': 'AI Smart Search',
    'hero.form.modeManual': 'Classic Filter',
    'hero.form.switchToFilters': 'Use Filters',
    'hero.form.switchToAI': 'Try AI Search',
    'hero.form.aiPlaceholder': "e.g., 'I want a modern 3-bedroom house in Kimironko with a view, under 60M RWF'",
    'hero.form.searchAI': 'Generate Results',
    //----------------- Auth
    'auth.login.heroTitle': 'Verified Property. Secure Future.',
    'auth.login.heroSubtitle': 'Join the first platform in Rwanda that integrates NLA verification directly into every listing. Zero fraud, 100% transparency.',
    'auth.login.welcomeBack': 'Welcome Back',
    'auth.login.enterDetails': 'Please enter your details to access your dashboard.',
    'auth.login.emailLabel': 'Email or Phone',
    'auth.login.passwordLabel': 'Password',
    'auth.login.forgotPassword': 'Forgot Password?',
    'auth.login.rememberMe': 'Remember me',
    'auth.login.submitButton': 'Sign In',
    'auth.login.noAccount': "Don't have an account?",
    'auth.login.registerLink': 'Create one now',
    //-----------Register
    'auth.register.title': 'Create Account',
    'auth.register.subtitle': 'Join SafeLand to buy, sell, and verify property.',
    'auth.register.step1Title': 'Select Identity Type',
    'auth.register.nid': 'Rwandan National ID',
    'auth.register.passport': 'Foreign Passport',
    'auth.register.continue': 'Continue',
    'auth.register.uploadPassport': 'Upload Passport Page',
    'auth.register.uploadHint': 'Click to upload or drag and drop (JPG, PNG, PDF)',
    'auth.register.fullName': 'Full Legal Name',
    'auth.register.phone': 'Phone Number',
    'auth.register.email': 'Email Address',
    'auth.register.nidNumber': 'National ID Number',
    'auth.register.country': 'Country of Origin',
    'auth.register.residence': 'Are you currently residing in Rwanda?',
    'auth.register.submit': 'Create Account',
    'auth.register.back': 'Back',
    'auth.register.loginLink': 'Already have an account?',
    'auth.register.login': 'Log In',
  },
  FR: {
    // mission vision values
    'mission.title': 'Notre Mission',
    'mission.desc': 'Révolutionner le secteur immobilier rwandais en établissant un marché axé sur la vérification qui élimine la fraude grâce à une intégration directe avec l\'Office National des Terres (NLA) et au verrouillage des transactions par la blockchain, tout en offrant aux parties prenantes des évaluations transparentes basées sur l\'IA et des analyses de marché en temps réel.',
    'vision.title': 'Notre Vision',
    'vision.desc': 'Devenir la norme numérique de confiance immobilière en Rwanda, créant un avenir où le transfert de propriété est instantané, sécurisé et accessible à tous.',
    'values.integrity': 'Intégrité',
    'values.innovation': 'Innovation',
    'values.access': 'Accessibilité',
    //hero market analyiss
    'ml.title': 'Prévisions du Marché par IA',
    'ml.subtitle': 'Analyses prédictives identifiant les zones à haut rendement avant le marché.',
    'ml.confidence': 'Score de Confiance IA',
    'ml.predicted': 'Prévision 2026',
    'ml.historical': 'Données Historiques',
    'ml.btn.analyze': 'Analyser le rapport',
    'ml.btn.assets': 'Voir les actifs à',
    // our professional agencies
    'community.title': 'Notre Impact & Réseau',
    'community.subtitle': 'Rencontrez les meilleurs acteurs du marché immobilier rwandais.',
    'community.stats.volume': 'Volume des Ventes',
    'community.stats.sold': 'Propriétés Vendues',
    'community.stats.agents': 'Agents Actifs',
    'community.agents.title': 'Agents les Mieux Notés',
    'community.agencies.title': 'Agences Partenaires',
    'community.cta.title': 'Êtes-vous un professionnel de l\'immobilier ?',
    'community.cta.subtitle': 'Rejoignez SafeLand pour accéder à des leads vérifiés et des outils numériques.',
    'community.cta.button': 'Demande d\'adhésion',
    //hot deals section based on users live location
    'hotDeals.title': 'Bonnes Affaires Près de Chez Vous',
    'hotDeals.subtitle': 'Nous avons trouvé des annonces vérifiées dans votre région.',
    'hotDeals.locating': 'Localisation en cours...',
    'hotDeals.locationFound': 'Emplacement Vérifié',
    'hotDeals.updateLocation': 'Changer de lieu',
    'hotDeals.viewDeal': 'Voir l\'offre',
    'hotDeals.exclusive': 'Exclusif',
    //Footer Component
    'footer.mission': 'SafeLand Rwanda est la première place de marché immobilier centralisée et intégrée à la NLA, garantissant zéro fraude.',
    'footer.newsletter.title': 'Restez informé',
    'footer.newsletter.subtitle': 'Recevez les dernières annonces vérifiées et les tendances du marché.',
    'footer.newsletter.placeholder': 'Entrez votre adresse email',
    'footer.newsletter.button': 'S\'abonner',
    'footer.links.company': 'Société',
    'footer.links.marketplace': 'Marché',
    'footer.links.support': 'Support',
    'footer.contact.title': 'Contactez-nous',
    'footer.rights': 'Tous droits réservés.',
    'footer.privacy': 'Politique de confidentialité',
    'footer.terms': 'Conditions d\'utilisation',
    // listing page
    'market.title': 'Trouvez votre propriété idéale',
    'market.subtitle': 'Parcourez des annonces vérifiées à travers le Rwanda, des maisons résidentielles aux terrains d\'investissement.',
    'market.category.houses': 'Maisons & Villas Résidentielles',
    'market.category.apartments': 'Appartements Modernes',
    'market.category.land': 'Terrains & Parcelles',
    'market.category.commercial': 'Immobilier Commercial',
    'market.viewAll': 'Voir tout',
    'market.filter.all': 'Tout',
    'market.filter.buy': 'A Vendre',
    'market.filter.rent': 'A Louer',
    'card.verified': 'Vérifié',
    //dsahabord page
    'dash.nav.overview': 'Vue d\'ensemble',
    'dash.nav.properties': 'Propriétés',
    'dash.nav.users': 'Utilisateurs',
    'dash.nav.analytics': 'Analytique',
    'dash.nav.settings': 'Paramètres',
    'dash.stats.totalSales': 'Ventes Totales',
    'dash.stats.activeListings': 'Annonces Actives',
    'dash.stats.verifiedUsers': 'Utilisateurs Vérifiés',
    'dash.welcome': 'Bon retour, Admin',
    'dash.subtitle': 'Voici ce qui se passe avec vos propriétés aujourd\'hui.',
    //Error 404 Page
    'error.404.title': 'Page Non Trouvée',
    'error.404.subtitle': 'Nous n\'avons pas pu localiser la page ou la propriété. Elle a peut-être été vendue ou déplacée.',
    'error.404.backHome': 'Retour à l\'accueil',
    'error.404.search': 'Chercher des biens',
    'error.404.support': 'Contacter le support',
    //forgot password
    'auth.forgot.title': 'Réinitialiser le mot de passe',
    'auth.forgot.subtitle': 'Entrez votre email pour recevoir les instructions de réinitialisation.',
    'auth.forgot.emailLabel': 'Adresse Email Enregistrée',
    'auth.forgot.submit': 'Envoyer le lien',
    'auth.forgot.backToLogin': 'Retour à la connexion',
    'auth.forgot.successTitle': 'Vérifiez votre email',
    'auth.forgot.successSubtitle': 'Nous avons envoyé un lien de réinitialisation à',
    'auth.forgot.resend': 'Email non reçu ?',
    'auth.forgot.resendLink': 'Renvoyer',
    // Navigation
    'nav.home': 'Accueil',
    'nav.marketTrends': 'Tendance du marché',
    'nav.about': 'À propos',
    'nav.services': 'Services',
    'nav.properties': 'Propriétés',
    'nav.properties.buy': 'Acheter un bien',
    'nav.properties.sell': 'Vendre un bien',
    'nav.properties.commercial': 'Bâtiments commerciaux',
    'nav.properties.houses': 'Maisons & Appartements',
    'nav.properties.land': 'Terrains & Parcelles',
    'nav.blockers': 'Contraintes',
    'nav.hotDeals': 'Offres spéciales',

    // TopBar
    'topbar.login': 'Connexion',
    'topbar.register': 'Inscription',
    'topbar.toggleTheme': 'Changer le thème',

    // Common
    'common.language.en': 'Anglais',
    'common.language.fr': 'Français',
    'common.language.kin': 'Kinyarwanda',
    // hero section home
    'hero.badge': 'Vérification Intégrée NLA',
    'hero.headline.part1': 'Achetez Terres & Maisons au Rwanda',
    'hero.headline.part2': 'Sans Risque.',
    'hero.subheadline.part1': 'Le premier marché décentralisé alimenté par la',
    'hero.subheadline.part2': 'vérification NLA',
    'hero.subheadline.part3': 'et l\'IA. Nous assurons que chaque titre de propriété est authentique, chaque propriétaire est vérifié, et chaque transaction est transparente.',
    'hero.stats.verifiedTitles': 'Titres Vérifiés',
    'hero.stats.zero': 'Zéro',
    'hero.stats.fraudTolerance': 'Tolérance à la Fraude',
    'hero.cta.exploreMap': 'Explorer la Carte',
    'hero.cta.listProperty': 'Lister un Bien',
    'hero.tabs.buy': 'Acheter',
    'hero.tabs.rent': 'Louer',
    'hero.tabs.land': 'Terrain',
    'hero.form.location': 'Localisation',
    'hero.form.locationPlaceholder': 'Kigali, Gasabo, Kimironko...',
    'hero.form.propertyType': 'Type de Propriété',
    'hero.propertyTypes.residential': 'Maison Résidentielle',
    'hero.propertyTypes.commercial': 'Bâtiment Commercial',
    'hero.propertyTypes.land': 'Terrain Vide / Parcelle',
    'hero.propertyTypes.apartment': 'Appartement',
    'hero.form.minPrice': 'Prix Minimum (RWF)',
    'hero.form.minPricePlaceholder': 'Min',
    'hero.form.maxPrice': 'Prix Maximum (RWF)',
    'hero.form.maxPricePlaceholder': 'Max',
    'hero.form.searchButton': 'Trouver {{propertyType}}',
    'hero.backgroundAlt': 'Immobilier Moderne au Rwanda',
    // --- NEW AI SEARCH KEYS ---
    'hero.form.modeAI': 'Recherche IA',
    'hero.form.modeManual': 'Filtres Classiques',
    'hero.form.switchToFilters': 'Utiliser les Filtres',
    'hero.form.switchToAI': 'Essayer l\'IA',
    'hero.form.aiPlaceholder': "ex: 'Je cherche une maison moderne de 3 chambres à Kimironko avec vue, moins de 60M RWF'",
    'hero.form.searchAI': 'Générer les Résultats',
    //----------------- Auth
    'auth.login.heroTitle': 'Propriété Vérifiée. Avenir Sûr.',
    'auth.login.heroSubtitle': 'Rejoignez la première plateforme au Rwanda qui intègre la vérification NLA directement dans chaque annonce. Zéro fraude, 100% transparence.',
    'auth.login.welcomeBack': 'Bon retour',
    'auth.login.enterDetails': 'Veuillez entrer vos coordonnées pour accéder à votre tableau de bord.',
    'auth.login.emailLabel': 'Adresse Email ou Téléphone',
    'auth.login.passwordLabel': 'Mot de passe',
    'auth.login.forgotPassword': 'Mot de passe oublié ?',
    'auth.login.rememberMe': 'Se souvenir de moi',
    'auth.login.submitButton': 'Se connecter',
    'auth.login.noAccount': "Vous n'avez pas de compte ?",
    'auth.login.registerLink': 'Créer un compte',
    //-----------------Register
    'auth.register.title': 'Créer un compte',
    'auth.register.subtitle': 'Rejoignez SafeLand pour acheter, vendre et vérifier.',
    'auth.register.step1Title': "Type d'identité",
    'auth.register.nid': 'Carte d\'identité Rwandaise',
    'auth.register.passport': 'Passeport Étranger',
    'auth.register.continue': 'Continuer',
    'auth.register.uploadPassport': 'Télécharger le passeport',
    'auth.register.uploadHint': 'Cliquez ou glissez-déposez (JPG, PNG)',
    'auth.register.fullName': 'Nom complet',
    'auth.register.phone': 'Numéro de téléphone',
    'auth.register.email': 'Adresse Email',
    'auth.register.nidNumber': 'Numéro CNI',
    'auth.register.country': 'Pays d\'origine',
    'auth.register.residence': 'Résidez-vous actuellement au Rwanda ?',
    'auth.register.submit': 'S\'inscrire',
    'auth.register.back': 'Retour',
    'auth.register.loginLink': 'Vous avez déjà un compte ?',
    'auth.register.login': 'Connexion',
  },
  KIN: {
    // mission vision values
    'mission.title': 'Intego Yacu',
    'mission.desc': 'Kuzana impinduramatwara mu rwego rw\'imitungo itimukanwa mu Rwanda, twubaka isoko rishingiye ku kugenzura (verification-first) rica burundu ubutekamutwe binyuze mu gukorana n\'Ikigo cy\'Ubutaka (NLA) no gukoresha Blockchain, ndetse no guha abafatanyabikorwa igenagaciro ryo ku rwego rwo hejuru rishingiye ku bwenge bw\'ubukorano (AI).',
    'vision.title': 'Icyerekezo Cyacu',
    'vision.desc': 'Kuba igisubizo cyizewe mu by\'ubutaka muri Rwanda yose, aho guhererekanya ubutaka bizajya bikorwa ako kanya, mu mutekano usesuye kandi bishobokera buri wese.',
    'values.integrity': 'Ubunyangamugayo',
    'values.innovation': 'Guhanga Udushya',
    'values.access': 'Kugera kuri Bose',
    //hero market analyiss
    'ml.title': 'Ikoranabuhanga ry\'Isoko',
    'ml.subtitle': 'Ikoranabuhanga rihanura aho isoko riganisha mbere yuko biba.',
    'ml.confidence': 'Icyizere cya AI',
    'ml.predicted': 'Biteganijwe 2026',
    'ml.historical': 'Amakuru yashize',
    'ml.btn.analyze': 'Sesengura Raporo',
    'ml.btn.assets': 'Reba imitungo i',
    // our professional agencies
    'community.title': 'Ibyo Twagezeho',
    'community.subtitle': 'Menya abakomisiyoneri b\'indashyikirwa bayoboye isoko ry\'u Rwanda.',
    'community.stats.volume': 'Agaciro k\'ibyagurishijwe',
    'community.stats.sold': 'Imitungo Yagurishijwe',
    'community.stats.agents': 'Abakomisiyoneri',
    'community.agents.title': 'Abakomisiyoneri b\'Indashyikirwa',
    'community.agencies.title': 'Amakompanyi Yizewe',
    'community.cta.title': 'Uri umunyamwuga mu by\'imitungo?',
    'community.cta.subtitle': 'Iyandikishe kuri SafeLand ubone abakiriya beza n\'uburyo bwo gukora bwihuse.',
    'community.cta.button': 'Saba Kwinjira',
    //hot deals section based on users live location
    'hotDeals.title': 'Igiciro Cyiza Hafi Yawe',
    'hotDeals.subtitle': 'Twabonye inzu n\'ibibanza byagenzuwe aho uherereye.',
    'hotDeals.locating': 'Turimo gushaka aho uri...',
    'hotDeals.locationFound': 'Aho uherereye',
    'hotDeals.updateLocation': 'Hindura',
    'hotDeals.viewDeal': 'Reba',
    'hotDeals.exclusive': 'Umwihariko',
    //Footer Component
    'footer.mission': 'SafeLand Rwanda niyo platform yambere ikorana na NLA kugirango habeho umucyo no kurwanya ubushukanyi.',
    'footer.newsletter.title': 'Amakuru Mashya',
    'footer.newsletter.subtitle': 'Iyandikishe kugirango ujye ubona inzu n\'ibibanza bishya byagenzuwe.',
    'footer.newsletter.placeholder': 'Andika imeyili yawe',
    'footer.newsletter.button': 'Iyandikishe',
    'footer.links.company': 'Kompanyi',
    'footer.links.marketplace': 'Isoko',
    'footer.links.support': 'Ubufasha',
    'footer.contact.title': 'Duhamagare',
    'footer.rights': 'Uburenganzira bwose burubahirijwe.',
    'footer.privacy': 'Amategeko y\'ibanga',
    'footer.terms': 'Amabwiriza',
    // listing page
    'market.title': 'Shaka Umutungo Ukwiriye',
    'market.subtitle': 'Reba imitungo yagenzuwe mu Rwanda hose, kuva ku nzu zo guturamo kugeza ku bibanza.',
    'market.category.houses': 'Inzu zisanzwe & Villas',
    'market.category.apartments': 'Aparutimanu zigezweho',
    'market.category.land': 'Ubutaka & Ibibanza',
    'market.category.commercial': 'Inzu z\'Ubucuruzi',
    'market.viewAll': 'Reba byose',
    'market.filter.all': 'Byose',
    'market.filter.buy': 'Kugura',
    'market.filter.rent': 'Gukodesha',
    'card.verified': 'Byagenzuwe',
    //dashbaord page design
    'dash.nav.overview': 'Incamake',
    'dash.nav.properties': 'Imitungo',
    'dash.nav.users': 'Abakoresha',
    'dash.nav.analytics': 'Imibare',
    'dash.nav.settings': 'Igenamiterere',
    'dash.stats.totalSales': 'Ibyagurishijwe',
    'dash.stats.activeListings': 'Imitungo iri kwisoko',
    'dash.stats.verifiedUsers': 'Abagenzuwe',
    'dash.welcome': 'Murakaza neza, Admin',
    'dash.subtitle': 'Dore uko isoko ryifashe uyumunsi.',
    //error 404 page not found
    'error.404.title': 'Ibyo ushaka Ntibyabonetse',
    'error.404.subtitle': 'Ntabwo tubashije kubona paji cyangwa umutungo mushaka. Wenda byagurishijwe cyangwa byimuwe.',
    'error.404.backHome': 'Subira Ahabanza',
    'error.404.search': 'Shakisha',
    'error.404.support': 'Ubufasha',
    // Fogot Password
    'auth.forgot.title': 'Hindura Ijambo ry\'ibanga',
    'auth.forgot.subtitle': 'Andika imeyili yawe tukoherereze amabwiriza yo guhindura ijambo ry\'ibanga.',
    'auth.forgot.emailLabel': 'Imeyili yawe',
    'auth.forgot.submit': 'Ohereza',
    'auth.forgot.backToLogin': 'Subira ahabanza',
    'auth.forgot.successTitle': 'Reba muri email yawe',
    'auth.forgot.successSubtitle': 'Twohereje amabwiriza kuri',
    'auth.forgot.resend': 'Ntuyibonye?',
    'auth.forgot.resendLink': 'Ohereza nanone',
    // Navigation
    'nav.home': 'Ahabanza',
    'nav.about': 'Ibyerekeye',
    'nav.marketTrends': 'Imigendekere y\'Isoko',
    'nav.services': 'Serivisi',
    'nav.properties': 'Imitungo',
    'nav.properties.buy': 'Gura Imitungo',
    'nav.properties.sell': 'Gurisha Imitungo',
    'nav.properties.commercial': 'Amazu y\'Ubucuruzi',
    'nav.properties.houses': 'Amazu n\'Amazu',
    'nav.properties.land': 'Ubutaka & Utuntu',
    'nav.blockers': 'Ibizitire',
    'nav.hotDeals': 'Ibyiza byihuse',

    // TopBar
    'topbar.login': 'Injira',
    'topbar.register': 'Iyandikishe',
    'topbar.toggleTheme': 'Hindura Imiterere',

    // Common
    'common.language.en': 'Icyongereza',
    'common.language.fr': 'Igifaransa',
    'common.language.kin': 'Kinyarwanda',
    // hero section home
    'hero.badge': 'Ibyemezo by\'Indangamuntu NLA',
    'hero.headline.part1': 'Gura Ubutaka & Amazu mu Rwanda',
    'hero.headline.part2': 'Nta Kaga.',
    'hero.subheadline.part1': 'Isoko ya mbere itunganyijwe ikoresheje',
    'hero.subheadline.part2': 'ibyemezo bya NLA',
    'hero.subheadline.part3': 'na AI. Dushaka kumenya neza ko buri nyandiko y\'ubutaka ari yo, umunyamibyara wese ari we, kandi buri mucuruzi ugaragara.',
    'hero.stats.verifiedTitles': 'Inyandiko Zemejwe',
    'hero.stats.zero': 'Zeru',
    'hero.stats.fraudTolerance': 'Kwemerera Ubujiji',
    'hero.cta.exploreMap': 'Shakisha Ikarita',
    'hero.cta.listProperty': 'Shyiraho Umutungo',
    'hero.tabs.buy': 'Gura',
    'hero.tabs.rent': 'Kodesha',
    'hero.tabs.land': 'Ubutaka',
    'hero.form.location': 'Aho biherereye',
    'hero.form.locationPlaceholder': 'Kigali, Gasabo, Kimironko...',
    'hero.form.propertyType': 'Ubwoko bw\'Umutungo',
    'hero.propertyTypes.residential': 'Inzu yo Gutura',
    'hero.propertyTypes.commercial': 'Inzu y\'Ubucuruzi',
    'hero.propertyTypes.land': 'Ubutaka / Utuntu',
    'hero.propertyTypes.apartment': 'Aparutimanu',
    'hero.form.minPrice': 'Igiciro Gito (RWF)',
    'hero.form.minPricePlaceholder': 'Gito',
    'hero.form.maxPrice': 'Igiciro Kinini (RWF)',
    'hero.form.maxPricePlaceholder': 'Kinini',
    'hero.form.searchButton': 'Shakisha {{propertyType}}',
    'hero.backgroundAlt': 'Imidugudu Mishya mu Rwanda',
    // --- NEW AI SEARCH KEYS ---
    'hero.form.modeAI': 'Ishakisha ry\'Ubwenge (AI)',
    'hero.form.modeManual': 'Gushaka Bisanzwe',
    'hero.form.switchToFilters': 'Koresha Akayunguruzo',
    'hero.form.switchToAI': 'Gerageza AI',
    'hero.form.aiPlaceholder': "Urugero: 'Ndashaka inzu igezweho y\'ibyumba 3 Kimironko, ifite view, munsi ya miliyoni 60'",
    'hero.form.searchAI': 'Shaka Ibisubizo',

    //-----------------auth
    'auth.login.heroTitle': 'Umutungo Wizewe. Ejo Heza.',
    'auth.login.heroSubtitle': 'Injira muri platform ya mbere mu Rwanda ikorana na NLA kugenzura ibyangombwa bya buri mutungo. Nta bushukanyi, umucyo 100%.',
    'auth.login.welcomeBack': 'Murakaza neza',
    'auth.login.enterDetails': 'Andika imyirondoro yawe kugirango winjire.',
    'auth.login.emailLabel': 'Imeyili (Email) cg Telefoni',
    'auth.login.passwordLabel': 'Ijambo ry\'ibanga',
    'auth.login.forgotPassword': 'Wibagiwe ijambo ry\'ibanga?',
    'auth.login.rememberMe': 'Ubutaha ntunsabe kwinjira',
    'auth.login.submitButton': 'Injira',
    'auth.login.noAccount': "Ntabwo ufite konti?",
    'auth.login.registerLink': 'Fungura konti',
    //-----------------Register
    'auth.register.title': 'Fungura Konti',
    'auth.register.subtitle': 'Injira muri SafeLand ubugure, ugurishe kandi ugenzure.',
    'auth.register.step1Title': 'Hitamo Ubwoko bw\'Irangamuntu',
    'auth.register.nid': 'Indangamuntu y\'u Rwanda',
    'auth.register.passport': 'Pasiporo y\'Abanyamahanga',
    'auth.register.continue': 'Komeza',
    'auth.register.uploadPassport': 'Shyiraho ifoto ya Pasiporo',
    'auth.register.uploadHint': 'Kanda hano cyangwa ukurure ifoto (JPG, PNG)',
    'auth.register.fullName': 'Amazina yose',
    'auth.register.phone': 'Nimero ya Telefoni',
    'auth.register.email': 'Imeyili',
    'auth.register.nidNumber': 'Nimero y\'Indangamuntu',
    'auth.register.country': 'Igihugu ukomokamo',
    'auth.register.residence': 'Ese uba mu Rwanda?',
    'auth.register.submit': 'Iyandikishe',
    'auth.register.back': 'Subira inyuma',
    'auth.register.loginLink': 'Usanganywe konti?',
    'auth.register.login': 'Injira',

  },
};