export const translations = {
  EN: {
    //hero section after
    'features.title': 'Why Choose SafeLand?',
    'features.subtitle': 'We are revolutionizing Rwandan real estate with technology that guarantees security and transparency.',
    'features.card1.title': '100% NLA Verified',
    'features.card1.desc': 'Every plot and house is cross-checked against the National Land Authority registry automatically.',
    'features.card2.title': 'Zero Fraud Guarantee',
    'features.card2.desc': 'Our biometric ID checks and ownership verification ensure you never deal with scammers.',
    'features.card3.title': 'Instant Transfers',
    'features.card3.desc': 'Digital agreements and smart contracts speed up the buying process from months to days.',
    'features.imageCaption.title': 'Digital Land Titles',
    'features.imageCaption.desc': 'Access your NLA-verified documents instantly from anywhere in the world.',
    
    //Footer Component
    'footer.mission': 'SafeLand Rwanda is the first centralized, NLA-integrated real estate marketplace ensuring zero fraud and 100% transparency.',
    'footer.newsletter.title': 'Stay Updated',
    'footer.newsletter.subtitle': 'Get the latest verified listings and market trends delivered to your inbox.',
    'footer.newsletter.placeholder': 'Enter your email address',
    'footer.newsletter.button': 'Subscribe',
    'footer.links.company': 'Company',
    'footer.links.marketplace': 'Marketplace',
    'footer.links.support': 'Support',
    'footer.contact.title': 'Contact Us',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    //Listing Page
    'market.title': 'Find Your Perfect Property',
    'market.subtitle': 'Browse verified listings across Rwanda, from residential homes to prime investment land.',
    'market.category.houses': 'Residential Houses & Villas',
    'market.category.apartments': 'Modern Apartments',
    'market.category.land': 'Land & Plots',
    'market.category.commercial': 'Commercial Real Estate',
    'market.viewAll': 'View All',
    'market.filter.all': 'All',
    'market.filter.buy': 'For Sale',
    'market.filter.rent': 'For Rent',
    'card.verified': 'Verified',
    // dashbaord content 
    'dash.nav.overview': 'Overview',
    'dash.nav.properties': 'Properties',
    'dash.nav.users': 'User Management',
    'dash.nav.analytics': 'Analytics',
    'dash.nav.settings': 'Settings',
    'dash.stats.totalSales': 'Total Sales',
    'dash.stats.activeListings': 'Active Listings',
    'dash.stats.verifiedUsers': 'Verified Users',
    'dash.welcome': 'Welcome back, Admin',
    'dash.subtitle': 'Here is what is happening with your properties today.',
    //Not Found Page
    'error.404.title': 'Page Not Found',
    'error.404.subtitle': 'We couldn’t locate the page or property you are looking for. It might have been sold or moved.',
    'error.404.backHome': 'Back to Safety',
    'error.404.search': 'Search Properties',
    'error.404.support': 'Contact Support',
    //Forgot PAssword
    'auth.forgot.title': 'Reset Password',
    'auth.forgot.subtitle': 'Enter your email and we’ll send you instructions to reset your password.',
    'auth.forgot.emailLabel': 'Registered Email Address',
    'auth.forgot.submit': 'Send Reset Link',
    'auth.forgot.backToLogin': 'Back to Login',
    'auth.forgot.successTitle': 'Check your email',
    'auth.forgot.successSubtitle': 'We have sent a password reset link to',
    'auth.forgot.resend': 'Didn’t receive the email? Click to resend',
    'auth.forgot.resendLink': 'Resend',
    // Navigation
    'nav.home': 'Home',
    'nav.marketTrends': 'Market Trends',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.properties': 'Properties',
    'nav.properties.buy': 'Buy Property',
    'nav.properties.sell': 'Sell Property',
    'nav.properties.commercial': 'Commercial Buildings',
    'nav.properties.houses': 'Houses & Apartments',
    'nav.properties.land': 'Land & Plots',
    'nav.blockers': 'Blockers',
    'nav.hotDeals': 'Hot Deals',

    // TopBar
    'topbar.login': 'Login',
    'topbar.register': 'Register',
    'topbar.toggleTheme': 'Toggle Theme',

    // Common
    'common.language.en': 'English',
    'common.language.fr': 'French',
    'common.language.kin': 'Kinyarwanda',

    // Mobile Menu
    'mobile.menu': 'Menu',
    // for hero section home
    'hero.badge': 'NLA Integrated Verification',
    'hero.headline.part1': 'Buy Land & Homes in Rwanda',
    'hero.headline.part2': 'Without the Risk.',
    'hero.subheadline.part1': 'The first decentralized marketplace powered by',
    'hero.subheadline.part2': 'NLA verification',
    'hero.subheadline.part3': 'and AI. We ensure every title deed is real, every owner is verified, and every transaction is transparent.',
    'hero.stats.verifiedTitles': 'Verified Titles',
    'hero.stats.zero': 'Zero',
    'hero.stats.fraudTolerance': 'Fraud Tolerance',
    'hero.cta.exploreMap': 'Explore Map',
    'hero.cta.listProperty': 'List Property',
    'hero.tabs.buy': 'Buy',
    'hero.tabs.rent': 'Rent',
    'hero.tabs.land': 'Land',
    'hero.form.location': 'Location',
    'hero.form.locationPlaceholder': 'Kigali, Gasabo, Kimironko...',
    'hero.form.propertyType': 'Property Type',
    'hero.propertyTypes.residential': 'Residential House',
    'hero.propertyTypes.commercial': 'Commercial Building',
    'hero.propertyTypes.land': 'Empty Plot / Land',
    'hero.propertyTypes.apartment': 'Apartment',
    'hero.form.minPrice': 'Min Price (RWF)',
    'hero.form.minPricePlaceholder': 'Min',
    'hero.form.maxPrice': 'Max Price (RWF)',
    'hero.form.maxPricePlaceholder': 'Max',
    'hero.form.searchButton': 'Find {{propertyType}}',
    'hero.backgroundAlt': 'Modern Real Estate in Rwanda',
    // --- NEW AI SEARCH KEYS ---
    'hero.form.modeAI': 'AI Smart Search',
    'hero.form.modeManual': 'Classic Filter',
    'hero.form.switchToFilters': 'Use Filters',
    'hero.form.switchToAI': 'Try AI Search',
    'hero.form.aiPlaceholder': "e.g., 'I want a modern 3-bedroom house in Kimironko with a view, under 60M RWF'",
    'hero.form.searchAI': 'Generate Results',
    //----------------- Auth
    'auth.login.heroTitle': 'Verified Property. Secure Future.',
    'auth.login.heroSubtitle': 'Join the first platform in Rwanda that integrates NLA verification directly into every listing. Zero fraud, 100% transparency.',
    'auth.login.welcomeBack': 'Welcome Back',
    'auth.login.enterDetails': 'Please enter your details to access your dashboard.',
    'auth.login.emailLabel': 'Email or Phone',
    'auth.login.passwordLabel': 'Password',
    'auth.login.forgotPassword': 'Forgot Password?',
    'auth.login.rememberMe': 'Remember me',
    'auth.login.submitButton': 'Sign In',
    'auth.login.noAccount': "Don't have an account?",
    'auth.login.registerLink': 'Create one now',
    //-----------Register
    'auth.register.title': 'Create Account',
    'auth.register.subtitle': 'Join SafeLand to buy, sell, and verify property.',
    'auth.register.step1Title': 'Select Identity Type',
    'auth.register.nid': 'Rwandan National ID',
    'auth.register.passport': 'Foreign Passport',
    'auth.register.continue': 'Continue',
    'auth.register.uploadPassport': 'Upload Passport Page',
    'auth.register.uploadHint': 'Click to upload or drag and drop (JPG, PNG, PDF)',
    'auth.register.fullName': 'Full Legal Name',
    'auth.register.phone': 'Phone Number',
    'auth.register.email': 'Email Address',
    'auth.register.nidNumber': 'National ID Number',
    'auth.register.country': 'Country of Origin',
    'auth.register.residence': 'Are you currently residing in Rwanda?',
    'auth.register.submit': 'Create Account',
    'auth.register.back': 'Back',
    'auth.register.loginLink': 'Already have an account?',
    'auth.register.login': 'Log In',
  },
  FR: {
    //hero section after
    'features.title': 'Pourquoi choisir SafeLand ?',
    'features.subtitle': 'Nous révolutionnons l\'immobilier rwandais avec une technologie garantissant sécurité et transparence.',
    'features.card1.title': 'Vérifié NLA à 100%',
    'features.card1.desc': 'Chaque parcelle et maison est automatiquement vérifiée auprès du registre de l\'Autorité Nationale des Terres.',
    'features.card2.title': 'Garantie Zéro Fraude',
    'features.card2.desc': 'Nos contrôles biométriques et la vérification de propriété vous protègent contre les escrocs.',
    'features.card3.title': 'Transferts Instantanés',
    'features.card3.desc': 'Les accords numériques et contrats intelligents accélèrent le processus d\'achat de plusieurs mois à quelques jours.',
    'features.imageCaption.title': 'Titres Fonciers Numériques',
    'features.imageCaption.desc': 'Accédez instantanément à vos documents vérifiés par la NLA, où que vous soyez.',
    //Footer Component
    'footer.mission': 'SafeLand Rwanda est la première place de marché immobilier centralisée et intégrée à la NLA, garantissant zéro fraude.',
    'footer.newsletter.title': 'Restez informé',
    'footer.newsletter.subtitle': 'Recevez les dernières annonces vérifiées et les tendances du marché.',
    'footer.newsletter.placeholder': 'Entrez votre adresse email',
    'footer.newsletter.button': 'S\'abonner',
    'footer.links.company': 'Société',
    'footer.links.marketplace': 'Marché',
    'footer.links.support': 'Support',
    'footer.contact.title': 'Contactez-nous',
    'footer.rights': 'Tous droits réservés.',
    'footer.privacy': 'Politique de confidentialité',
    'footer.terms': 'Conditions d\'utilisation',
    // listing page
    'market.title': 'Trouvez votre propriété idéale',
    'market.subtitle': 'Parcourez des annonces vérifiées à travers le Rwanda, des maisons résidentielles aux terrains d\'investissement.',
    'market.category.houses': 'Maisons & Villas Résidentielles',
    'market.category.apartments': 'Appartements Modernes',
    'market.category.land': 'Terrains & Parcelles',
    'market.category.commercial': 'Immobilier Commercial',
    'market.viewAll': 'Voir tout',
    'market.filter.all': 'Tout',
    'market.filter.buy': 'A Vendre',
    'market.filter.rent': 'A Louer',
    'card.verified': 'Vérifié',
    //dsahabord page
    'dash.nav.overview': 'Vue d\'ensemble',
    'dash.nav.properties': 'Propriétés',
    'dash.nav.users': 'Utilisateurs',
    'dash.nav.analytics': 'Analytique',
    'dash.nav.settings': 'Paramètres',
    'dash.stats.totalSales': 'Ventes Totales',
    'dash.stats.activeListings': 'Annonces Actives',
    'dash.stats.verifiedUsers': 'Utilisateurs Vérifiés',
    'dash.welcome': 'Bon retour, Admin',
    'dash.subtitle': 'Voici ce qui se passe avec vos propriétés aujourd\'hui.',
    //Error 404 Page
    'error.404.title': 'Page Non Trouvée',
    'error.404.subtitle': 'Nous n\'avons pas pu localiser la page ou la propriété. Elle a peut-être été vendue ou déplacée.',
    'error.404.backHome': 'Retour à l\'accueil',
    'error.404.search': 'Chercher des biens',
    'error.404.support': 'Contacter le support',
    //forgot password
    'auth.forgot.title': 'Réinitialiser le mot de passe',
    'auth.forgot.subtitle': 'Entrez votre email pour recevoir les instructions de réinitialisation.',
    'auth.forgot.emailLabel': 'Adresse Email Enregistrée',
    'auth.forgot.submit': 'Envoyer le lien',
    'auth.forgot.backToLogin': 'Retour à la connexion',
    'auth.forgot.successTitle': 'Vérifiez votre email',
    'auth.forgot.successSubtitle': 'Nous avons envoyé un lien de réinitialisation à',
    'auth.forgot.resend': 'Email non reçu ?',
    'auth.forgot.resendLink': 'Renvoyer',
    // Navigation
    'nav.home': 'Accueil',
    'nav.marketTrends': 'Tendance du marché',
    'nav.about': 'À propos',
    'nav.services': 'Services',
    'nav.properties': 'Propriétés',
    'nav.properties.buy': 'Acheter un bien',
    'nav.properties.sell': 'Vendre un bien',
    'nav.properties.commercial': 'Bâtiments commerciaux',
    'nav.properties.houses': 'Maisons & Appartements',
    'nav.properties.land': 'Terrains & Parcelles',
    'nav.blockers': 'Contraintes',
    'nav.hotDeals': 'Offres spéciales',

    // TopBar
    'topbar.login': 'Connexion',
    'topbar.register': 'Inscription',
    'topbar.toggleTheme': 'Changer le thème',

    // Common
    'common.language.en': 'Anglais',
    'common.language.fr': 'Français',
    'common.language.kin': 'Kinyarwanda',
    // hero section home
    'hero.badge': 'Vérification Intégrée NLA',
    'hero.headline.part1': 'Achetez Terres & Maisons au Rwanda',
    'hero.headline.part2': 'Sans Risque.',
    'hero.subheadline.part1': 'Le premier marché décentralisé alimenté par la',
    'hero.subheadline.part2': 'vérification NLA',
    'hero.subheadline.part3': 'et l\'IA. Nous assurons que chaque titre de propriété est authentique, chaque propriétaire est vérifié, et chaque transaction est transparente.',
    'hero.stats.verifiedTitles': 'Titres Vérifiés',
    'hero.stats.zero': 'Zéro',
    'hero.stats.fraudTolerance': 'Tolérance à la Fraude',
    'hero.cta.exploreMap': 'Explorer la Carte',
    'hero.cta.listProperty': 'Lister un Bien',
    'hero.tabs.buy': 'Acheter',
    'hero.tabs.rent': 'Louer',
    'hero.tabs.land': 'Terrain',
    'hero.form.location': 'Localisation',
    'hero.form.locationPlaceholder': 'Kigali, Gasabo, Kimironko...',
    'hero.form.propertyType': 'Type de Propriété',
    'hero.propertyTypes.residential': 'Maison Résidentielle',
    'hero.propertyTypes.commercial': 'Bâtiment Commercial',
    'hero.propertyTypes.land': 'Terrain Vide / Parcelle',
    'hero.propertyTypes.apartment': 'Appartement',
    'hero.form.minPrice': 'Prix Minimum (RWF)',
    'hero.form.minPricePlaceholder': 'Min',
    'hero.form.maxPrice': 'Prix Maximum (RWF)',
    'hero.form.maxPricePlaceholder': 'Max',
    'hero.form.searchButton': 'Trouver {{propertyType}}',
    'hero.backgroundAlt': 'Immobilier Moderne au Rwanda',
    // --- NEW AI SEARCH KEYS ---
    'hero.form.modeAI': 'Recherche IA',
    'hero.form.modeManual': 'Filtres Classiques',
    'hero.form.switchToFilters': 'Utiliser les Filtres',
    'hero.form.switchToAI': 'Essayer l\'IA',
    'hero.form.aiPlaceholder': "ex: 'Je cherche une maison moderne de 3 chambres à Kimironko avec vue, moins de 60M RWF'",
    'hero.form.searchAI': 'Générer les Résultats',
    //----------------- Auth
    'auth.login.heroTitle': 'Propriété Vérifiée. Avenir Sûr.',
    'auth.login.heroSubtitle': 'Rejoignez la première plateforme au Rwanda qui intègre la vérification NLA directement dans chaque annonce. Zéro fraude, 100% transparence.',
    'auth.login.welcomeBack': 'Bon retour',
    'auth.login.enterDetails': 'Veuillez entrer vos coordonnées pour accéder à votre tableau de bord.',
    'auth.login.emailLabel': 'Adresse Email ou Téléphone',
    'auth.login.passwordLabel': 'Mot de passe',
    'auth.login.forgotPassword': 'Mot de passe oublié ?',
    'auth.login.rememberMe': 'Se souvenir de moi',
    'auth.login.submitButton': 'Se connecter',
    'auth.login.noAccount': "Vous n'avez pas de compte ?",
    'auth.login.registerLink': 'Créer un compte',
    //-----------------Register
    'auth.register.title': 'Créer un compte',
    'auth.register.subtitle': 'Rejoignez SafeLand pour acheter, vendre et vérifier.',
    'auth.register.step1Title': "Type d'identité",
    'auth.register.nid': 'Carte d\'identité Rwandaise',
    'auth.register.passport': 'Passeport Étranger',
    'auth.register.continue': 'Continuer',
    'auth.register.uploadPassport': 'Télécharger le passeport',
    'auth.register.uploadHint': 'Cliquez ou glissez-déposez (JPG, PNG)',
    'auth.register.fullName': 'Nom complet',
    'auth.register.phone': 'Numéro de téléphone',
    'auth.register.email': 'Adresse Email',
    'auth.register.nidNumber': 'Numéro CNI',
    'auth.register.country': 'Pays d\'origine',
    'auth.register.residence': 'Résidez-vous actuellement au Rwanda ?',
    'auth.register.submit': 'S\'inscrire',
    'auth.register.back': 'Retour',
    'auth.register.loginLink': 'Vous avez déjà un compte ?',
    'auth.register.login': 'Connexion',
  },
  KIN: {
    //hero section after
    'features.title': 'Kuki Wahitamo SafeLand?',
    'features.subtitle': 'Tuzanye ikoranabuhanga mu by\'imitungo mu Rwanda ryizeza umutekano n\'umucyo.',
    'features.card1.title': 'Bigenzuwe na NLA 100%',
    'features.card1.desc': 'Buri kibanza n\'inzu bigenzurwa mu gitabo cy\'Ikigo cy\'Ubutaka mu Rwanda (NLA) mu buryo bwikora.',
    'features.card2.title': 'Nta Bushukanyi',
    'features.card2.desc': 'Igenzura ry\'irangamuntu n\'ibyangombwa by\'umutungo bituma wirinda abatekamutwe.',
    'features.card3.title': 'Ihererekanya Ryihuse',
    'features.card3.desc': 'Amasezerano y\'ikoranabuhanga atuma kugura no kugurisha byihuta cyane kurusha mbere.',
    'features.imageCaption.title': 'Ibyangombwa by\'Ubutaka',
    'features.imageCaption.desc': 'Bona ibyangombwa byawe byagenzuwe na NLA ako kanya, aho waba uri hose.',
    //Footer Component
    'footer.mission': 'SafeLand Rwanda niyo platform yambere ikorana na NLA kugirango habeho umucyo no kurwanya ubushukanyi.',
    'footer.newsletter.title': 'Amakuru Mashya',
    'footer.newsletter.subtitle': 'Iyandikishe kugirango ujye ubona inzu n\'ibibanza bishya byagenzuwe.',
    'footer.newsletter.placeholder': 'Andika imeyili yawe',
    'footer.newsletter.button': 'Iyandikishe',
    'footer.links.company': 'Kompanyi',
    'footer.links.marketplace': 'Isoko',
    'footer.links.support': 'Ubufasha',
    'footer.contact.title': 'Duhamagare',
    'footer.rights': 'Uburenganzira bwose burubahirijwe.',
    'footer.privacy': 'Amategeko y\'ibanga',
    'footer.terms': 'Amabwiriza',
    // listing page
    'market.title': 'Shaka Umutungo Ukwiriye',
    'market.subtitle': 'Reba imitungo yagenzuwe mu Rwanda hose, kuva ku nzu zo guturamo kugeza ku bibanza.',
    'market.category.houses': 'Inzu zisanzwe & Villas',
    'market.category.apartments': 'Aparutimanu zigezweho',
    'market.category.land': 'Ubutaka & Ibibanza',
    'market.category.commercial': 'Inzu z\'Ubucuruzi',
    'market.viewAll': 'Reba byose',
    'market.filter.all': 'Byose',
    'market.filter.buy': 'Kugura',
    'market.filter.rent': 'Gukodesha',
    'card.verified': 'Byagenzuwe',
    //dashbaord page design
    'dash.nav.overview': 'Incamake',
    'dash.nav.properties': 'Imitungo',
    'dash.nav.users': 'Abakoresha',
    'dash.nav.analytics': 'Imibare',
    'dash.nav.settings': 'Igenamiterere',
    'dash.stats.totalSales': 'Ibyagurishijwe',
    'dash.stats.activeListings': 'Imitungo iri kwisoko',
    'dash.stats.verifiedUsers': 'Abagenzuwe',
    'dash.welcome': 'Murakaza neza, Admin',
    'dash.subtitle': 'Dore uko isoko ryifashe uyumunsi.',
    //error 404 page not found
    'error.404.title': 'Ibyo ushaka Ntibyabonetse',
    'error.404.subtitle': 'Ntabwo tubashije kubona paji cyangwa umutungo mushaka. Wenda byagurishijwe cyangwa byimuwe.',
    'error.404.backHome': 'Subira Ahabanza',
    'error.404.search': 'Shakisha',
    'error.404.support': 'Ubufasha',
    // Fogot Password
    'auth.forgot.title': 'Hindura Ijambo ry\'ibanga',
    'auth.forgot.subtitle': 'Andika imeyili yawe tukoherereze amabwiriza yo guhindura ijambo ry\'ibanga.',
    'auth.forgot.emailLabel': 'Imeyili yawe',
    'auth.forgot.submit': 'Ohereza',
    'auth.forgot.backToLogin': 'Subira ahabanza',
    'auth.forgot.successTitle': 'Reba muri email yawe',
    'auth.forgot.successSubtitle': 'Twohereje amabwiriza kuri',
    'auth.forgot.resend': 'Ntuyibonye?',
    'auth.forgot.resendLink': 'Ohereza nanone',
    // Navigation
    'nav.home': 'Ahabanza',
    'nav.about': 'Ibyerekeye',
    'nav.marketTrends': 'Imigendekere y\'Isoko',
    'nav.services': 'Serivisi',
    'nav.properties': 'Imitungo',
    'nav.properties.buy': 'Gura Imitungo',
    'nav.properties.sell': 'Gurisha Imitungo',
    'nav.properties.commercial': 'Amazu y\'Ubucuruzi',
    'nav.properties.houses': 'Amazu n\'Amazu',
    'nav.properties.land': 'Ubutaka & Utuntu',
    'nav.blockers': 'Ibizitire',
    'nav.hotDeals': 'Ibyiza byihuse',

    // TopBar
    'topbar.login': 'Injira',
    'topbar.register': 'Iyandikishe',
    'topbar.toggleTheme': 'Hindura Imiterere',

    // Common
    'common.language.en': 'Icyongereza',
    'common.language.fr': 'Igifaransa',
    'common.language.kin': 'Kinyarwanda',
    // hero section home
    'hero.badge': 'Ibyemezo by\'Indangamuntu NLA',
    'hero.headline.part1': 'Gura Ubutaka & Amazu mu Rwanda',
    'hero.headline.part2': 'Nta Kaga.',
    'hero.subheadline.part1': 'Isoko ya mbere itunganyijwe ikoresheje',
    'hero.subheadline.part2': 'ibyemezo bya NLA',
    'hero.subheadline.part3': 'na AI. Dushaka kumenya neza ko buri nyandiko y\'ubutaka ari yo, umunyamibyara wese ari we, kandi buri mucuruzi ugaragara.',
    'hero.stats.verifiedTitles': 'Inyandiko Zemejwe',
    'hero.stats.zero': 'Zeru',
    'hero.stats.fraudTolerance': 'Kwemerera Ubujiji',
    'hero.cta.exploreMap': 'Shakisha Ikarita',
    'hero.cta.listProperty': 'Shyiraho Umutungo',
    'hero.tabs.buy': 'Gura',
    'hero.tabs.rent': 'Kodesha',
    'hero.tabs.land': 'Ubutaka',
    'hero.form.location': 'Aho biherereye',
    'hero.form.locationPlaceholder': 'Kigali, Gasabo, Kimironko...',
    'hero.form.propertyType': 'Ubwoko bw\'Umutungo',
    'hero.propertyTypes.residential': 'Inzu yo Gutura',
    'hero.propertyTypes.commercial': 'Inzu y\'Ubucuruzi',
    'hero.propertyTypes.land': 'Ubutaka / Utuntu',
    'hero.propertyTypes.apartment': 'Aparutimanu',
    'hero.form.minPrice': 'Igiciro Gito (RWF)',
    'hero.form.minPricePlaceholder': 'Gito',
    'hero.form.maxPrice': 'Igiciro Kinini (RWF)',
    'hero.form.maxPricePlaceholder': 'Kinini',
    'hero.form.searchButton': 'Shakisha {{propertyType}}',
    'hero.backgroundAlt': 'Imidugudu Mishya mu Rwanda',
    // --- NEW AI SEARCH KEYS ---
    'hero.form.modeAI': 'Ishakisha ry\'Ubwenge (AI)',
    'hero.form.modeManual': 'Gushaka Bisanzwe',
    'hero.form.switchToFilters': 'Koresha Akayunguruzo',
    'hero.form.switchToAI': 'Gerageza AI',
    'hero.form.aiPlaceholder': "Urugero: 'Ndashaka inzu igezweho y\'ibyumba 3 Kimironko, ifite view, munsi ya miliyoni 60'",
    'hero.form.searchAI': 'Shaka Ibisubizo',

    //-----------------auth
    'auth.login.heroTitle': 'Umutungo Wizewe. Ejo Heza.',
    'auth.login.heroSubtitle': 'Injira muri platform ya mbere mu Rwanda ikorana na NLA kugenzura ibyangombwa bya buri mutungo. Nta bushukanyi, umucyo 100%.',
    'auth.login.welcomeBack': 'Murakaza neza',
    'auth.login.enterDetails': 'Andika imyirondoro yawe kugirango winjire.',
    'auth.login.emailLabel': 'Imeyili (Email) cg Telefoni',
    'auth.login.passwordLabel': 'Ijambo ry\'ibanga',
    'auth.login.forgotPassword': 'Wibagiwe ijambo ry\'ibanga?',
    'auth.login.rememberMe': 'Ubutaha ntunsabe kwinjira',
    'auth.login.submitButton': 'Injira',
    'auth.login.noAccount': "Ntabwo ufite konti?",
    'auth.login.registerLink': 'Fungura konti',
    //-----------------Register
    'auth.register.title': 'Fungura Konti',
    'auth.register.subtitle': 'Injira muri SafeLand ubugure, ugurishe kandi ugenzure.',
    'auth.register.step1Title': 'Hitamo Ubwoko bw\'Irangamuntu',
    'auth.register.nid': 'Indangamuntu y\'u Rwanda',
    'auth.register.passport': 'Pasiporo y\'Abanyamahanga',
    'auth.register.continue': 'Komeza',
    'auth.register.uploadPassport': 'Shyiraho ifoto ya Pasiporo',
    'auth.register.uploadHint': 'Kanda hano cyangwa ukurure ifoto (JPG, PNG)',
    'auth.register.fullName': 'Amazina yose',
    'auth.register.phone': 'Nimero ya Telefoni',
    'auth.register.email': 'Imeyili',
    'auth.register.nidNumber': 'Nimero y\'Indangamuntu',
    'auth.register.country': 'Igihugu ukomokamo',
    'auth.register.residence': 'Ese uba mu Rwanda?',
    'auth.register.submit': 'Iyandikishe',
    'auth.register.back': 'Subira inyuma',
    'auth.register.loginLink': 'Usanganywe konti?',
    'auth.register.login': 'Injira',

  },
};